### ISSUE TITLE
Scraping don't works correctly + Solution

### ISSUE THREAD

**Issue by WulfmanGer** [Voljega/amiga4recalbox#12]
Problem:
Recommend scraper at Recalbox: screenscraper.fr. The other two scraper aren't works fine (mame etc.). But Screenscrapers needs an information about the platform.

Following happens: 
Scrape an Amiga-Game: Screenscraper doesn't recognise the Platform: your game could be an Megadrive, SNES, NES ... Game but no Amiga. If the game exists on THIS Plaforms! Only Amiga? No Chance! Next "Problem": You scrape an Game-Cover-Picture from Megadrive, SNES etc. Not pretty!

Solution:
The problem results in es_systems.cfg
<fullname>amiga600</fullname>
<name>amiga600</name>
<platform>amiga600</platform>
(same with 1200, CD32)

Fullname: i've changes this to **Amiga 600**, **Amiga 1200** and **Amiga CD32** [with spaces after Amiga].  Really needed? It doesn't hurt. Looks better too:) 
Name: **don't change**! Internal - to adress themes etc.
Platform: CHANGE! change to "**amiga**"

(not tested: change only "platform"; my es_systems.cfg has new fullname and platform; since your old setup without any problems)

After Change:
Scraping will give you now only Amiga-Versions. Game-Cover from CD32 etc. Of course it depends on what is stored in Screenscraper.

Good Example:
California Games
Your es_systems.cfg: several hits. Megadrive etc.
After Change: 2 Hits: California Games and California Games II - both: Amiga

**Comment by Voljega** [comment]
OK, so if I understand it right I just have to make the following corrections in es_systems.cfg :
`<fullname>amiga600</fullname>` should become `<fullname>Amiga 600</fullname>`
`<platform>amiga600</platform>` should become `<platform>amiga</platform>`

alike for amiga1200

but for CD32 should the platform also be `amiga` or `amigacd32` or `amiga cd32` ?

**Comment by WulfmanGer** [comment]
CD32 also change to amiga (without cd32)

**Comment by Voljega** [comment]
Corrected in https://github.com/Voljega/amiga4recalbox/commit/36266a71ec9a0a2748010f522ff76ce8030423ee
