### ISSUE TITLE
Dark screen

### ISSUE THREAD

**Issue by Garg54** [Voljega/amiga4recalbox#14]
Hello,
I followed your tutorial,  put the kickstart from my "amiga forever" and i used the last recalbox release.
Amiga is now visible in my emulation station but when i run a game i have a dark screen.

![20171213_225012](https://user-images.githubusercontent.com/3314858/33990183-5e4459ce-e0ca-11e7-9124-26349fd6a1e2.jpg)
![20171213_225024](https://user-images.githubusercontent.com/3314858/33990184-5e617eb4-e0ca-11e7-9c5f-226747bbe5d5.jpg)

Any idea for me pls ?
Thanks
Seb

**Comment by Voljega** [comment]
Does the green number in the bottom right corner move or is it 'stuck' on one number ?
If you open the GUI (Start on your controller) do you see the adf disk ?
Did you put all needed kickstarts with the right MD5 ?
Did you try with several games ?

**Comment by Garg54** [comment]
Does the green number in the bottom right corner move or is it 'stuck' on one number ?
_number is changing_
If you open the GUI (Start on your controller) do you see the adf disk ?
_yes_
Did you put all needed kickstarts with the right MD5 ?
_i didn't verify as it's from my amiga forever :(. i will check tonight_
Did you try with several games ?
_swos nitro advantage tennis and wings ..._

Thanks for your answer ... and your work

**Comment by Voljega** [comment]
If the number is changing regularly and not cyclically it means the game is loading, just wait a few minutes (sole games can take up to 5mn to launch)

**Comment by Garg54** [comment]
Yesterday, I let it during more than one hour :)

**Comment by Voljega** [comment]
Can you upload your adfs on zippyshare or somewhere ?

**Comment by Garg54** [comment]
Yes i will do it this evening

**Comment by SebC** [comment]
You can find here : 
https://www.claudel.lu/voljega/kick.zip
Pls say me when you downloaded them and I will delete it.
Thnaks

**Comment by Garg54** [comment]
md5sum kick13.rom 
40e325f9774c1e902a170a572a4a3a96                                                                                                                                                   
md5sum kick20.rom                                                                                                                      
c56ca2a3c644d53e780a7e4dbdc6b699                                                                                                                                                 
md5sum kick31.rom 
dc3f5e4698936da34186d596c53681ab
My md5 are differents :(

**Comment by Voljega** [comment]
ok then try to get the right kickstarts.

anyway I meant your ADF files not your kickstarts ;)

**Comment by Garg54** [comment]
ok sorry ^^
i will purchase edition 2017 of amiga forever and try it (my edition is from 2015)

**Comment by Voljega** [comment]
try looking on the internet it's much more simple

because my kickstarts date back to 2015 too

**Comment by Garg54** [comment]
It's working with amiga forever 2017. My previous version was from 2014 so you are not compatible with it for info
Thks

**Comment by Voljega** [comment]
cool ! weLL I guess it's an amiberry limitation
