### ISSUE TITLE
Bad mapping

### ISSUE THREAD

**Issue by Garg54** [Voljega/amiga4recalbox#17]
Hello,

I installed your version, but since the last update of recalbox, my buttons mapping is wrong. 
To go up, i have to use left;
To go down i have to use right
To go right, i have to use down
To go left, i have to use up
In recalbox it's ok, in all others emulators it's ok, just in amiga games it's wrong. i try to reconfigure it in uae but no success, do you have an idea pls ?

thanks
Seb

**Comment by Voljega** [comment]
It's not possible to configure in uae with this version of amiberry

I frankly don't know what to say, I myself even never tried to install Recalbox update over my version, I did a reinstall from scratch....

And I would do that if I were you, unless your Recalbox is heavily configured... 
If so, try to erase everything in configgen for amiberry and get the files from recalbox configgen gitlab to restart on fresh version

**Comment by Garg54** [comment]
ok :( thks
i will make a new install
