### ISSUE TITLE
WHDL games do not properly save

### ISSUE THREAD

**Issue by Voljega** [Voljega/amiga4recalbox#5]
Save files are written to disk after quitting a game. (but they appear during the game in Theme Park)

NoWriteCache should be activated (everything is writen directly to disk and not after leaving the game)

https://circuit-board.de/forum/index.php/Thread/18365-A500-mit-WHDLoad-Cannon-Fodder-Savegame-ist-nach-Neustart-weg-Problem-gelöst/
http://eab.abime.net/showthread.php?t=64818
http://www.minimig.net/viewtopic.php?f=3&t=356

**Comment by HoraceAndTheSpider** [comment]
You can just add NoWriteCache to s:Whdload-prefs

**Comment by Voljega** [comment]
Thank you !

well it's already in there : https://github.com/Voljega/amiga4recalbox/blob/master/installAmiga/whdl/S/WHDLoad.prefs

I suppose I just have to remove the `;` before it

**Comment by HoraceAndTheSpider** [comment]
Yes, exactly that :)

**Comment by Voljega** [comment]
done in https://github.com/Voljega/amiga4recalbox/commit/971654a5dfc46560393abeee0065a6fe75241724
